name: Build and release tarballs

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Snapshot
        uses: goreleaser/goreleaser-action@v5
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          args: release --clean --snapshot

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
